config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    member do
      post :confirm
    end
  end
  resources :contract_plans
  devise_for :users
  resources :users

  authenticated :user do
    root "contract_plans#index", as: :authenticated_root
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contract_plan.rb
class ContractPlan < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :confirmed_by_user, class_name: 'User', optional: true

  scope :waiting_approval_orders, -> { where.not(slip_image: nil) }
  scope :confirmed_orders, -> { where.not(confirmed_at: nil) }
  scope :bought_orders, -> { where(confirmed_at: nil, slip_image: nil) }

  mount_uploader :slip_image, SlipImageUploader

  validates_presence_of :user

  def approve_by(admin)
    self.confirmed_by_user = admin
    self.confirmed_at = DateTime.now
    save
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

end

app/controllers/contract_plans_controller.rb
class ContractPlansController < ApplicationController
  before_action :set_contract_plan, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :index

  # GET /contract_plans
  # GET /contract_plans.json
  def index
    @contract_plans = ContractPlan.all
  end

  # GET /contract_plans/1
  # GET /contract_plans/1.json
  def show
  end

  # GET /contract_plans/new
  def new
    @contract_plan = ContractPlan.new
  end

  # GET /contract_plans/1/edit
  def edit
  end

  # POST /contract_plans
  # POST /contract_plans.json
  def create
    @contract_plan = ContractPlan.new(contract_plan_params)

    respond_to do |format|
      if @contract_plan.save
        format.html { redirect_to @contract_plan, notice: 'Contract plan was successfully created.' }
        format.json { render :show, status: :created, location: @contract_plan }
      else
        format.html { render :new }
        format.json { render json: @contract_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contract_plans/1
  # PATCH/PUT /contract_plans/1.json
  def update
    respond_to do |format|
      if @contract_plan.update(contract_plan_params)
        format.html { redirect_to @contract_plan, notice: 'Contract plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @contract_plan }
      else
        format.html { render :edit }
        format.json { render json: @contract_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contract_plans/1
  # DELETE /contract_plans/1.json
  def destroy
    @contract_plan.destroy
    respond_to do |format|
      format.html { redirect_to contract_plans_url, notice: 'Contract plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contract_plan
      @contract_plan = ContractPlan.find(params[:id])
      authorize @contract_plan
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contract_plan_params
      params.require(:contract_plan).permit(:hash_rate, :price, :contract_long)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy, :confirm]

  # GET /orders
  # GET /orders.json
  def index
    if current_user.admin?
      @order_type = params[:order_type]
      @orders = case @order_type
                when "waiting_approval"
                  @title = "Waiting for approval orders"
                  Order.waiting_approval_orders
                when "confirmed"
                  @title = "Approved orders"
                  Order.confirmed_orders
                else
                  @title = "Waiting for money transfer"
                  Order.bought_orders
                end
    else
      @title = "My orders"
      @orders = current_user.orders
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(create_order_params)
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirm
    if current_user.admin?
      if @order.approve_by(current_user)
        respond_to do |format|
          format.html { redirect_to orders_url, notice: 'Order has been approved' }
          format.json { render json: {}, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to root, notice: 'Not Authorized' }
        format.json { render json: {}, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = if current_user.admin?
        Order.find(params[:id])
      else
        current_user.orders.find_by(params[:id])
      end
      authorize @order
    end

    def update_order_params
      params.require(:order).permit(:slip_image)
    end

    def create_order_params
      params[:order] = { user_id: current_user.id }
      params[:order].merge!(contract_plan.slice(:hash_rate, :price, :contract_long))
      params.require(:order).permit(:hash_rate, :price, :user_id, :contract_long)
    end

    def contract_plan
      return unless params[:contract_plan_id]
      @contract_plan ||= ContractPlan.find(params[:contract_plan_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contract_plans_helper.rb
module ContractPlansHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/contract_plans/_contract_plan.html.erb
<div class="col-12 col-md-4">
  <div class="statcard p-3 box">
    <span class="statcard-desc">Hash rate</span>
    <h3 class="statcard-number"><%= contract_plan.hash_rate %> MH/s</h3>
    <span class="statcard-desc">Price</span>
    <h3 class="statcard-number"><%= contract_plan.price %> THB</h3>
    <span class="statcard-desc">Contract Long</span>
    <h3 class="statcard-number"><%= contract_plan.contract_long
     %> months</h3>
    <br>
    <%= link_to 'Show', contract_plan, :class=>"btn-normal" %>

    <% if current_user.admin? %>
      <%= link_to 'Edit', edit_contract_plan_path(contract_plan), :class=>"btn-normal" %>
      <%= link_to 'Destroy', contract_plan, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn-normal" %>
    <% end %>
  </div>
</div>

app/views/contract_plans/_form.html.erb
<%= form_with(model: contract_plan, local: true) do |form| %>
  <% if contract_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contract_plan.errors.count, "error") %> prohibited this contract_plan from being saved:</h2>

      <ul>
      <% contract_plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :hash_rate %>
    <%= form.text_field :hash_rate, id: :contract_plan_hash_rate %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :contract_plan_price %>
  </div>

  <div class="field">
    <%= form.label :contract_long %>
    <%= form.number_field :contract_long, id: :contract_plan_contract_long %>
  </div>

  <div class="action">
    <%= form.submit %>
  </div>
<% end %>

app/views/contract_plans/edit.html.erb
<h1>Editing Contract Plan</h1>

<%= render 'form', contract_plan: @contract_plan %>

<%= link_to 'Show', @contract_plan, :class => "btn-normal"%>
<%= link_to 'Back', contract_plans_path, :class => "btn-normal"%>

app/views/contract_plans/index.html.erb
<!--<p id="notice"><%= notice %></p>-->

<h1>Contract Plans</h1>

<div class="summary-group row">
  <% @contract_plans.each do |contract_plan| %>
    <%= render contract_plan %>
  <% end %>
</div>

<br>

<%= link_to('New Contract Plan', new_contract_plan_path, class: "btn-highlight") if current_user.admin? %>

app/views/contract_plans/new.html.erb
<h1>New Contract Plan</h1>

<%= render 'form', contract_plan: @contract_plan %>

<%= link_to 'Back', contract_plans_path, :class => "btn-normal"%>

app/views/contract_plans/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Contract Confirmation</h2>

<div class="summary-group row">
  <div class="col-12 col-md-4">
    <div class="statcard p-3 box">
      <span class="statcard-desc">Hash rate</span>
      <h3 class="statcard-number"><%= @contract_plan.hash_rate %> MH/s</h3>
    </div>
  </div>
  <div class="col-12 col-md-4">
    <div class="statcard p-3 box">
      <span class="statcard-desc">Price</span>
      <h3 class="statcard-number"><%= @contract_plan.price %> THB</h3>
    </div>
  </div>
  <div class="col-12 col-md-4">
    <div class="statcard p-3 box">
      <span class="statcard-desc">Contract Long</span>
      <h3 class="statcard-number"><%= @contract_plan.contract_long %> Months</h3>
    </div>
  </div>
</div>

<%= link_to 'Buy', orders_path(contract_plan_id: @contract_plan), method: :post, data: { confirm: "Are you sure?" }, :class => "btn btn-primary"%>
<%= link_to 'Back', contract_plans_path, :class => "btn btn-secondary" %>
<%= link_to 'Edit', edit_contract_plan_path(@contract_plan), :class => "btn btn-secondary" if current_user.admin? %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container-header">

  <nav class="iconav">
    <%= link_to root_path, :class => 'iconav-brand' do %>
      <span class="desktop">SP</span>
      <span class="mobile"> Farming</span>
    <% end %>
    <div class="iconav-slider">
      <ul class="nav nav-pills iconav-nav flex-md-column">
        <li class="nav-item">
          <%= link_to root_path, title: "Home" , :data => { :toggle => 'tooltip', :placement => 'right', :container => 'body' },  :class => 'nav-link' do %>
            <div class="nav-icon">  
              <i class="fas fa-home"></i>
            </div>
            <small class="iconav-nav-label">Home</small>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to orders_path, title: "Orders" , :data => { :toggle => 'tooltip', :placement => 'right', :container => 'body' }, :class => 'nav-link' do %>
            <div class="nav-icon">
              <i class="fas fa-briefcase"></i>
            </div>
            <small class="iconav-nav-label">Orders</small>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to contract_plans_path, title: "Contract Plans" , :data => { :toggle => 'tooltip', :placement => 'right', :container => 'body' }, :class => 'nav-link' do %>
            <div class="nav-icon">
              <i class="fas fa-shopping-cart"></i>
            </div>
            <small class="iconav-nav-label">Contract Plans</small>
          <% end %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, title: "Log out" , :data => { :toggle => 'tooltip', :placement => 'right', :container => 'body' }, method: :delete,  :class => 'nav-link' do %>
              <div class="nav-icon">
                <i class="fas fa-sign-out-alt"></i>
              </div>
              <small class="iconav-nav-label">Log out</small>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to new_user_session_path, title: "Log in" , :data => { :toggle => 'tooltip', :placement => 'right', :container => 'body' } , :class => 'nav-link' do  %>
              <div class="nav-icon">
                <i class="fas fa-sign-in-alt"></i>
              </div>
              <small class="iconav-nav-label">Log in</small>
            <% end %>
          </li>
        <% end %>
        
        <!--<li class="nav-item">
          <a class="nav-link active" href="../icon-nav/index.html" title: "Icon-nav" data-toggle="tooltip" data-placement="right" data-container="body">
            <span class="icon icon-area-graph"></span>
            <small class="iconav-nav-label d-md-none">Icon nav</small>
          </a>
        </li>-->
        
        
      </ul>
    </div>
  </nav>

  <!--<nav class="navbar navbar-expand-sm fixed-top navbar-dark bg-dark app-navbar">
      <a class="navbar-brand" href="../index.html">
      SP Farming: Dashboard
    </a>
    <button class="navbar-toggler navbar-toggler-right d-md-none" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="nav navbar-nav mr-auto">
        <%= render 'layouts/navigation_links' %>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'active') %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to('Login', new_user_session_path)  %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>-->
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Spfarm" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Spfarm" %>">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :hash_rate %>
    <%= form.text_field :hash_rate, id: :order_hash_rate %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :order_price %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :order_user_id %>
  </div>

  <div class="field">
    <%= form.label :confirmed_at %>
    <%= form.datetime_select :confirmed_at, id: :order_confirmed_at %>
  </div>

  <div class="field">
    <%= form.label :confirmed_by_user_id %>
    <%= form.number_field :confirmed_by_user_id, id: :order_confirmed_by_user_id %>
  </div>

  <div class="field">
    <%= form.label :slip_image %>
    <%= form.file_field :slip_image, id: :order_slip_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order, :class=>"btn-normal" %>
<%= link_to 'Back', orders_path, :class=>"btn-normal" %>

app/views/orders/index.html.erb
<!--<p id="notice"><%= notice %></p>-->
<% if current_user.admin? %>
  <div class="btn-group dashhead-toolbar-item btn-group-thirds">
    <%= link_to "Waiting for image slip orders", orders_path(order_type: "bought_orders"), class: "btn btn-outline-primary #{ "active" if @order_type == "bought_orders" }" %>
    <%= link_to "Waiting for approval_orders", orders_path(order_type: "waiting_approval"), class: "btn btn-outline-primary #{ "active" if @order_type == "waiting_approval" }" %>
    <%= link_to "Approved orders", orders_path(order_type: "confirmed"), class: "btn btn-outline-primary #{ "active" if @order_type == "confirmed" }"  %>
  </div>
  <br>
  <br>
<% end %>

<h1><%= @title %></h1>
<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th class="header">Hash rate</th>
      <th class="header">Price</th>
      <th class="header">Contract Long (months)</th>
      <th class="header">User</th>
      <th class="header">Confirmed at</th>
      <th class="header">Slip image</th>
      <th colspan="3" class="header"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.hash_rate %> MH/s</td>
        <td><%= number_to_currency @order.price, unit: "THB" %></td>
        <td><%= order.contract_long %></td>
        <td><%= order.user_id %></td>
        <td><%= @order.confirmed_at.strftime('%c') %></td>
        <td><%= order.slip_image %></td>
        <td><%= link_to 'Show', order, :class=>"btn-normal"%></td>
        <td><%= link_to 'Edit', edit_order_path(order), :class=>"btn-normal" %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } , :class=>"btn-normal"%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Order', new_order_path, :class=>"btn-highlight" if current_user.admin? %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path, :class=>"btn-normal" %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Order: <%= @order.id %></h1>

<div class="hr-divider mt-5 mb-3">
  <h3 class="hr-divider-content hr-divider-heading">Order Detail:</h3>
</div>
<div class="summary-group row">
  <div class="col-12 col-md-4">
    <div class="statcard p-3 box">
      <span class="statcard-desc">Hash rate</span>
      <h3 class="statcard-number"><%= @order.hash_rate %> MH/s</h3>
    </div>
  </div>
  <div class="col-12 col-md-4">
    <div class="statcard p-3 box">
      <span class="statcard-desc">Price</span>
      <h3 class="statcard-number"><%= number_to_currency @order.price, unit: "THB" %></h3>
    </div>
  </div>
  <div class="col-12 col-md-4">
    <div class="statcard p-3 box">
      <span class="statcard-desc">Confirmed at</span>
      <h3 class="statcard-number"><%= @order.confirmed_at.strftime('%c') %></h3>
    </div>
  </div>
  <div class="col-12 col-md-4">
    <div class="statcard p-3 box">
      <span class="statcard-desc">Slip image</span>
      <div>
        <%= cl_image_tag @order.slip_image if @order.slip_image.present? %>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Back', orders_path, :class=>"btn-normal" %>

<% if current_user.admin? %>
  <div class="hr-divider mt-5 mb-3">
    <h3 class="hr-divider-content hr-divider-heading">Status</h3>
  </div>

  <div class="summary-group row">
    <div class="col-12 col-md-4">
      <div class="statcard p-3 box">
        <span class="statcard-desc">User</span>
        <h3 class="statcard-number"><%= @order.user.email %></h3>
      </div>
    </div>
    <div class="col-12 col-md-4">
      <div class="statcard p-3 box">
        <span class="statcard-desc">Confirmed by:</span>
        <h3 class="statcard-number"><%= @order.confirmed_by_user.email %></h3>
      </div>
    </div> 
  </div>
  <%= link_to 'Edit', edit_order_path(@order), :class=>"btn-highlight" %>
  <div class="hr-divider mt-5 mb-3">
    <h3 class="hr-divider-content hr-divider-heading">Administrator</h3>
  </div>
  <p>
    <strong>Confirm This order:</strong>
    <%= link_to 'Confirm', confirm_order_path(@order), method: :post, :class=>"btn-highlight btn-success" %>
  </p>
<% end %>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <div class="table-responsive">
        <table class="table">
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <%= render user %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<div class="summary-group row">
  <div class="col-12 col-md-4">
    <div class="statcard p-3 box">
      <span class="statcard-desc">Name</span>
      <h3 class="statcard-number"><%= @user.name if @user.name %></h3>
    </div>
  </div>
  <div class="col-12 col-md-4">
    <div class="statcard p-3 box">
      <span class="statcard-desc">Email</span>
      <h3 class="statcard-number"><%= @user.email if @user.email %></h3>
    </div>
  </div>
</div>

app/views/visitors/index.html.erb
<p><%= link_to 'Contract Plans', contract_plans_path, :class => "btn-normal" %></p>
<p><%= link_to 'Orders', orders_path, :class => "btn-normal" %></p>

<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>